import React from 'react'
import NavBar from './NavBar'
import './Aboutstyle.css'
const Home = () => {
  return (
    <div>
        <NavBar></NavBar>
      <div className="image">
    </div>

    <div className="over">
        CARBON FOOTPRINT</div>

    <div className="what">
        <h1>What is carbon footprint ?</h1>
        <p>A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.</p>
      
        <p>The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average carbon footprint is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.</p>
      
        <p>Lowering individual carbon footprints from 16 tons to 2 tons doesn’t happen overnight! By making small changes to our actions, like eating less meat, taking fewer connecting flights and line drying our clothes, we can start making a big difference.</p>
    </div>

    <div className="calculate">
        <h1>How to calculate it ?</h1>
        <p>Carbon Footprint = (electricity used*0.0023)+(diesel used*0.0063)+(petrol used*0.0072)+(water used*0.001*0.149)+(gas used*0.18316)+(paper used)*1.04</p>
    </div>
<div></div>
    </div>
  )
}

export default Home
